FIXUP: CHROMIUM: rk3399: Disable ddr clk timeout on suspend
arm64:allmodconfig fails to build.

ERROR: "rockchip_ddrclk_set_timeout_en" [drivers/devfreq/rk3399_dmc.ko]
undefined!

The rk3399_dmc driver can be built as module. Any functions it uses
need to be exported.

BUG=chrome-os-partner:62193
TEST=Build arm64:allmodconfig

Change-Id: I4c04ca87173d3a8803f81b84e04edff805384a2e
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/431819
Reviewed-by: Dmitry Torokhov <dtor@chromium.org>