ANDROID: cpufreq: interactive: drop cpufreq_{get,put}_global_kobject func calls
Upstream commit 8eec1020f0c0 (cpufreq: create cpu/cpufreq at boot time)
make sure that cpufreq sysfs entry get created at boot time, and there
is no need to create/destroy it on need basis anymore.

So drop deprecated cpufreq_{get,put}_global_kobject function calls which
otherwise result in following compilation errors:

drivers/cpufreq/cpufreq_interactive.c: In function 'cpufreq_governor_interactive':
drivers/cpufreq/cpufreq_interactive.c:1187:4: error: implicit declaration of function 'cpufreq_get_global_kobject' [-Werror=implicit-function-declaration]
    WARN_ON(cpufreq_get_global_kobject());
    ^
drivers/cpufreq/cpufreq_interactive.c:1197:5: error: implicit declaration of function 'cpufreq_put_global_kobject'[-Werror=implicit-function-declaration]
     cpufreq_put_global_kobject();
     ^

Signed-off-by: Amit Pundir <amit.pundir@linaro.org>
(cherry picked from https://android.googlesource.com/kernel/common android-4.4
 commit 287d9d0efbd378dc0d7919bc9820737c869f5c0b)

BUG=none
TEST=we can boot without big warnings:
[    3.214602] sysfs: cannot create duplicate filename '/devices/system/cpu/cpufreq'
[    3.222206] ------------[ cut here ]------------
[    3.226828] WARNING: at /mnt/host/source/src/third_party/kernel/v4.4/fs/sysfs/dir.c:31

Change-Id: Ica5864bcfbcf889d6021cd7e67e37f544f593592
Signed-off-by: Brian Norris <briannorris@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/345521
Reviewed-by: Guenter Roeck <groeck@google.com>