FIXUP: FROMLIST: mmc: sdhci-of-arasan: Add ability to export card clock
This patch fixes up commit 1c18e74e3f49 ("FROMLIST: mmc:
sdhci-of-arasan: Add ability to export card clock").  We landed v2
but then we posted v2.1 with fixes.  Specifically if COMMON_CLK was not
enabled, we'd get errors:

drivers/mmc/host/sdhci-of-arasan.c: In function 'sdhci_arasan_unregister_sdclk':
drivers/mmc/host/sdhci-of-arasan.c:455:2: error:
	implicit declaration of function 'of_clk_del_provider'

drivers/mmc/host/sdhci-of-arasan.c:92:16: error:
	field 'sdcardclk_hw' has incomplete type

BUG=chrome-os-partner:53445
TEST=Build mips:allmodconfig

Change-Id: I74a9d2ace38cead37f467447aa57c22741693f14
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Signed-off-by: Douglas Anderson <dianders@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/352881