UPSTREAM: tpm: select ANON_INODES for proxy driver
The newly added vtpmx driver fails to build if CONFIG_ANON_INODES
is disabled:

drivers/char/built-in.o: In function `vtpmx_fops_ioctl':
(.text+0x97f8): undefined reference to `anon_inode_getfile'

This adds a Kconfig 'select' statement to ensure it's always there
when we need it.

BUG=chrome-os-partner:54590
TEST=Build and boot on kevin, verify that /dev/tpm0 is present.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: 794c38e01358 ("tpm: Proxy driver for supporting multiple emulated TPMs")
Acked-by: Stefan Berger <stefanb@linux.vnet.ibm.com>
Acked-by: Jarkko Sakkinen <jarkko.sakkinen@linux.intel.com>
Signed-off-by: Jarkko Sakkinen <jarkko.sakkinen@linux.intel.com>
(cherry picked from commit 54745cb483392f9b94eb07e6cba05b07ea78dfcc
 git://git.infradead.org/users/jjs/linux-tpmdd.git master)
Signed-off-by: Andrey Pronin <apronin@chromium.org>

Change-Id: I145e59bff3131e4804c8b6ae0886937bdd7d9d70
Reviewed-on: https://chromium-review.googlesource.com/354874
Commit-Ready: Andrey Pronin <apronin@chromium.org>
Tested-by: Andrey Pronin <apronin@chromium.org>
Reviewed-by: Douglas Anderson <dianders@chromium.org>