CHROMIUM: timekeeping: Mark timekeeping_cycles_to_ns() as __maybe_unused
The function is not used in v4.4 (it is used by upstream). Adding the
attribute fixes the following warning:

kernel/time/timekeeping.c:321:19: error: unused function
    'timekeeping_cycles_to_ns' [-Werror,-Wunused-function]

BUG=chromium:702741
TEST=build with clang for gru

Change-Id: Icbc1e625f6e73e1a10b404eaac3df5228fa40fbb
Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/508104
Reviewed-by: Guenter Roeck <groeck@chromium.org>