CHROMIUM: [media] intel-ipu3: Remove redefinition of imgu_addr_t
The type imgu_addr_t is already defined in include/uapi/linux/intel-ipu3.h,
clang complains about the redefinition:

drivers/media/pci/intel/ipu3/ipu3-abi.h:379:13: error: redefinition of typedef 'imgu_addr_t' is a C11 feature [-Werror,-Wtypedef-redefinition]
typedef u32 imgu_addr_t;
            ^
include/uapi/linux/intel-ipu3.h:517:15: note: previous definition is here
typedef __u32 imgu_addr_t;
              ^

Fixes: 83b4ef8f1f2 ("CHROMIUM: [media] intel-ipu3: css: firmware management")

BUG=b:37020027, chromium:702741
TEST=build for squawks with clang

Change-Id: I297a49911dc2092a4b61575d9f899cde912aaba1
Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/568695
Reviewed-by: Ricky Liang <jcliang@chromium.org>
Reviewed-by: Tomasz Figa <tfiga@chromium.org>
Reviewed-by: Yong Zhi <yong.zhi@intel.com>