FIXUP: CHROMIUM: drm: bridge: Generic GPIO mux driver
Various test builds fail as follows.

drivers/gpu/drm/bridge/generic-gpio-mux.c:
	In function 'gpio_display_mux_det_threaded_handler':
drivers/gpu/drm/bridge/generic-gpio-mux.c:46:2: error:
	implicit declaration of function 'gpiod_get_value'
drivers/gpu/drm/bridge/generic-gpio-mux.c:
	In function 'gpio_display_mux_probe':
drivers/gpu/drm/bridge/generic-gpio-mux.c:200:3: error:
	implicit declaration of function 'devm_gpiod_get'
drivers/gpu/drm/bridge/generic-gpio-mux.c:200:33: error:
	'GPIOD_IN' undeclared

GPIO drivers depend on GPIOLIB.

BUG=chrome-os-partner:52354
TEST=Build s390:allmodconfig

Change-Id: Iad6494124a4e80745265c2df95a39313c56e09bd
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/455136
Reviewed-by: Nicolas Boichat <drinkcat@chromium.org>