CHROMIUM: google: vpd: Replace ioremap_cache() with memremap()
ioremap_cache() is deprecated and not or no longer supported on all
architectures. This can result in the following build error (seen
with mips:allmodconfig).

drivers/firmware/google/vpd.c: In function 'vpd_section_init':
drivers/firmware/google/vpd.c:151:2: error:
	implicit declaration of function 'ioremap_cache'

BUG=None
TEST=Load on system supporting vpd and ensure that it still works

Signed-off-by: Guenter Roeck <groeck@chromium.org>