FIXUP: BACKPORT: drm/fence: add fence to drm_pending_event
The backport removed the delete callback from struct drm_pending_event
but missed a number of callers. This results in the following build errors
when building various images.

drivers/gpu/drm/vc4/vc4_crtc.c: In function vc4_cancel_page_flip:
drivers/gpu/drm/vc4/vc4_crtc.c:511:24: error:
	struct drm_pending_event has no member named destroy

drivers/gpu/drm/vmwgfx/vmwgfx_fence.c: In function vmw_event_fence_fpriv_gone:
drivers/gpu/drm/vmwgfx/vmwgfx_fence.c:841:8: error:
	struct drm_pending_event has no member named destroy

drivers/gpu/drm/vmwgfx/vmwgfx_fence.c:
	In function vmw_event_fence_action_create:
drivers/gpu/drm/vmwgfx/vmwgfx_fence.c:1057:13: error:
	struct drm_pending_event has no member named destroy
drivers/gpu/drm/vmwgfx/vmwgfx_fence.c:1078:13: error:
	struct drm_pending_event has no member named destroy

drivers/gpu/drm/exynos/exynos_drm_drv.c: In function 'exynos_drm_postclose':
drivers/gpu/drm/exynos/exynos_drm_drv.c:387:4: error:
	'struct drm_pending_event' has no member named 'destroy'

drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_crtc.c:
	In function 'atmel_hlcdc_crtc_cancel_page_flip':
drivers/gpu/drm/atmel-hlcdc/atmel_hlcdc_crtc.c:294:14: error:
	'struct drm_pending_event' has no member named 'destroy'

drivers/gpu/drm/exynos/exynos_drm_g2d.c:
	In function 'exynos_g2d_set_cmdlist_ioctl':
drivers/gpu/drm/exynos/exynos_drm_g2d.c:1117:10: error:
	'struct drm_pending_event' has no member named 'destroy'

drivers/gpu/drm/exynos/exynos_drm_ipp.c: In function 'ipp_get_event':
drivers/gpu/drm/exynos/exynos_drm_ipp.c:651:9: error:
	'struct drm_pending_event' has no member named 'destroy'

drivers/gpu/drm/omapdrm/omap_crtc.c: In function 'omap_crtc_complete_page_flip':
drivers/gpu/drm/omapdrm/omap_crtc.c:282:14: error:
	'struct drm_pending_event' has no member named 'destroy'

drivers/gpu/drm/rcar-du/rcar_du_crtc.c:
	In function 'rcar_du_crtc_cancel_page_flip':
drivers/gpu/drm/rcar-du/rcar_du_crtc.c:299:14: error:
	'struct drm_pending_event' has no member named 'destroy'

drivers/gpu/drm/shmobile/shmob_drm_crtc.c:
	In function 'shmob_drm_crtc_cancel_page_flip':
drivers/gpu/drm/shmobile/shmob_drm_crtc.c:455:14: error:
	'struct drm_pending_event' has no member named 'destroy'

drivers/gpu/drm/tegra/dc.c: In function 'tegra_dc_cancel_page_flip':
drivers/gpu/drm/tegra/dc.c:1000:18: error:
	'struct drm_pending_event' has no member named 'destroy'

drivers/gpu/drm/tilcdc/tilcdc_crtc.c: In function 'tilcdc_crtc_cancel_page_flip':
drivers/gpu/drm/tilcdc/tilcdc_crtc.c:679:14: error:
	'struct drm_pending_event' has no member named 'destroy'

Remove the assignments to the no longer existing structure element,
and replace the callbacks with direct calls to kfree().

BUG=chromium:652865, chromium:654094
TEST=build x86_64:allmodconfig, arm:allmodconfig

Note for rebase to later kernels: Drop this and the associated backport.

Change-Id: Id857c22dca0fbdd1a761b1691e7a6ee92954d556
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/395631
Reviewed-by: Matthias Kaehlcke <mka@chromium.org>