CHROMIUM: Mark DRM_POWERVR_ROGUE[_1_7] as BROKEN
Builds with DRM_POWERVR_ROGUE or DRM_POWERVR_ROGUE_1_7 enabled fail with

drivers/gpu/drm/img-rogue/1.7/cache_rangebased.c:
	In function 'CacheOpSetTimeline':
drivers/gpu/drm/img-rogue/1.7/cache_rangebased.c:1683:2: error:
	implicit declaration of function 'sync_timeline_signal'

due to infrastructure changes. sync_timeline_signal() is now static and
can no longer be used by drivers.

BUG=b:64680718
TEST=Build arm64:allmodconfig

Change-Id: I6c51f476f0f955b98e75001e71f51b38b740339b
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/613503
Reviewed-by: Daniel Kurtz <djkurtz@chromium.org>