FIXUP: CHROMIUM: drm/rockchip: Disable VOP windows when PSR is active
arm:allmodconfig and arm64:allmodconfig fail to build.

ERROR: "rockchip_drm_set_win_enabled"
[drivers/gpu/drm/rockchip/analogix_dp-rockchip.ko] undefined!

Export the missing symbol.

BUG=chrome-os-partner:56429
TEST=Build arm64:allmodconfig

Change-Id: I602948a0537bc7dba35b6dda57e910ca2fcd8519
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/433373
Reviewed-by: Douglas Anderson <dianders@chromium.org>