FIXUP: CHROMIUM: drm/rockchip: cdn-dp: add cdn DP support for rk3399
The cdn-dp driver fails to build as follows if built as module for arm.

ERROR: "__aeabi_uldivmod" [drivers/gpu/drm/rockchip/cdn-dp-reg.ko] undefined!
ERROR: "cdn_dp_audio_config" [drivers/gpu/drm/rockchip/cdn-dp-core.ko]
	undefined!
ERROR: "cdn_dp_audio_stop" [drivers/gpu/drm/rockchip/cdn-dp-core.ko] undefined!
ERROR: "cdn_dp_audio_mute" [drivers/gpu/drm/rockchip/cdn-dp-core.ko] undefined!
ERROR: "cdn_dp_config_video" [drivers/gpu/drm/rockchip/cdn-dp-core.ko]
	undefined!
ERROR: "cdn_dp_set_video_status" [drivers/gpu/drm/rockchip/cdn-dp-core.ko]
	undefined!
ERROR: "cdn_dp_train_link" [drivers/gpu/drm/rockchip/cdn-dp-core.ko] undefined!
ERROR: "cdn_dp_set_host_cap" [drivers/gpu/drm/rockchip/cdn-dp-core.ko]
	undefined!
ERROR: "cdn_dp_get_hpd_status" [drivers/gpu/drm/rockchip/cdn-dp-core.ko]
	undefined!
ERROR: "cdn_dp_event_config" [drivers/gpu/drm/rockchip/cdn-dp-core.ko]
	undefined!
ERROR: "cdn_dp_load_firmware" [drivers/gpu/drm/rockchip/cdn-dp-core.ko]
	undefined!
ERROR: "cdn_dp_clock_reset" [drivers/gpu/drm/rockchip/cdn-dp-core.ko] undefined!
ERROR: "cdn_dp_set_fw_clk" [drivers/gpu/drm/rockchip/cdn-dp-core.ko] undefined!
ERROR: "cdn_dp_dpcd_read" [drivers/gpu/drm/rockchip/cdn-dp-core.ko] undefined!
ERROR: "cdn_dp_get_edid_block" [drivers/gpu/drm/rockchip/cdn-dp-core.ko]
	undefined!
ERROR: "cdn_dp_set_firmware_active" [drivers/gpu/drm/rockchip/cdn-dp-core.ko]
	undefined!

Problem is two-fold. First, the driver is actually built as two modules,
which is fixed by modifying the Makefile. Second, the driver uses 64-bit
divide operations, which is fixed by using do_div() and div_u64() as
needed.

BUG=chrome-os-partner:52872
TEST=Check DP display

Change-Id: I84872bca8974c6bbba5cecb266b8beca1b27e894
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/395611
Reviewed-by: Sean Paul <seanpaul@chromium.org>