FROMGIT: iio: magnetometer: Only declare ACPI table when ACPI is enable
Don't inflate the kernel size with data that isn't used. The conditional
declaration also fixes the following warning when building with clang:

drivers/iio/magnetometer/ak8975.c:704:36: error: variable 'ak_acpi_match'
  is not needed and will not be emitted
  [-Werror,-Wunneeded-internal-declaration]

BUG=chromium:702741
TEST=build for kevin with clang

Change-Id: I17a229b8073c89d99fc6da1a2a2a840f272672cb
Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Acked-by: Linus Walleij <linus.walleij@linaro.org>
Signed-off-by: Jonathan Cameron <jic23@kernel.org>
(cherry picked from git.kernel.org jic23/iio testing
commit 2aac3388f1682d6208f6759c338a7efa37b0deca)
Reviewed-on: https://chromium-review.googlesource.com/549656
Reviewed-by: Douglas Anderson <dianders@chromium.org>