FIXUP: CHROMIUM: usb: dwc3: support host mode for rockchip platform
In dwc3_rockchip_remove(), ensure that clocks are enabled before calling
of_platform_depopulate(). Without this change, running "modprobe -r
dwc3_rockchip; modprobe dwc3_rockchip" in a tight loop may result in
occassional crashes.

Also, hcd code reacts badly if PHYs are or were powered off when HCDs
are removed and/or inserted. Doing this may result in a hung task.

INFO: task kworker/4:1:100 blocked for more than 120 seconds.
Not tainted 4.4.14 #210
"echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
kworker/4:1     D ffffffc000204fd8     0   100      2 0x00000000
Workqueue: events dwc3_rockchip_otg_extcon_evt_work
Call trace:
[<ffffffc000204fd8>] __switch_to+0x9c/0xa8
[<ffffffc0009095fc>] __schedule+0x440/0x6d8
[<ffffffc000909928>] schedule+0x94/0xb4
[<ffffffc00090ca78>] schedule_timeout+0x44/0x27c
[<ffffffc00090a580>] wait_for_common+0xf8/0x198
[<ffffffc00090a648>] wait_for_completion+0x28/0x34
[<ffffffc000678d94>] xhci_configure_endpoint+0x20c/0x4b0
[<ffffffc000679684>] xhci_check_bandwidth+0x1a4/0x324
[<ffffffc00064bae4>] usb_hcd_alloc_bandwidth+0xb4/0x2c8
[<ffffffc00064e7e8>] usb_disable_device+0x17c/0x1c8
[<ffffffc0006461d8>] usb_disconnect+0x9c/0x1d0
[<ffffffc0006461c4>] usb_disconnect+0x88/0x1d0
[<ffffffc00064a750>] usb_remove_hcd+0xc8/0x1e0
[<ffffffc000660ec0>] dwc3_rockchip_otg_extcon_evt_work+0x54/0x184

To work around this problem, keep the PHY enabled while nothing is
connected, and power cycle it only after hcd removal.

Last but not least, the drive depends on CONFIG_COMMON_CLK, and may
otherwise cause the following build error.

drivers/usb/dwc3/dwc3-rockchip.c: In function 'dwc3_rockchip_probe':
drivers/usb/dwc3/dwc3-rockchip.c:251:2: error:
	implicit declaration of function 'of_clk_get_parent_count'

BUG=chrome-os-partner:52872,chrome-os-partner:55069, chrome-os-partner:56792, chrome-os-partner:57525
TEST=run "modprobe -r dwc3_rockchip; modprobe dwc3_rockchip" in tight loop
TEST=hotplug multi-function docks several times

Change-Id: Ia4c3d9a41871899d492822fd60358df4413d3d50
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/386387