FIXUP: BACKPORT: FROMLIST: PM / AVS: thermal: MT8173: Introduce support for SVS engine
Commit 88719cc27d275 ("BACKPORT: FROMLIST: PM / AVS: thermal: MT8173:
Introduce support for SVS engine") changed MTK_THERMAL from tristate
to bool, but neglected to update its dependencies. This results in

mtk_thermal.c:(.text+0x25fd87): undefined reference to `nvmem_cell_get'
mtk_thermal.c:(.text+0x25fde0): undefined reference to `nvmem_cell_read'
mtk_thermal.c:(.text+0x25fdf7): undefined reference to `nvmem_cell_put'
mtk_thermal.c:(.text+0x26079d): undefined reference to `nvmem_cell_get'
mtk_thermal.c:(.text+0x2607cf): undefined reference to `nvmem_cell_read'
mtk_thermal.c:(.text+0x2607e7): undefined reference to `nvmem_cell_put'

if MTK_THERMAL is built into the kernel and NVMEM is built as module.

BUG=chrome-os-partner:50411
TEST=Attempt to configure CONFIG_MTK_THERMAL=y and CONFIG_NVMEM=m.

Change-Id: Iffcfba2b86bcbc31075efcb9cd936dd4ec14281c
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/451720
Commit-Ready: Daniel Kurtz <djkurtz@chromium.org>
Reviewed-by: Nicolas Boichat <drinkcat@chromium.org>