CHROMIUM: MALI: Mark kbasep_jm_is_js_free() as __maybe_unused
The function kbasep_jm_is_js_free() is only used in an assertion and
therefore unused when debugging is not enabled. Adding the attribute
fixes the following warning when building with clang:

drivers/gpu/arm/midgard/backend/gpu/mali_kbase_jm_hw.c:46:19: error:
    unused function 'kbasep_jm_is_js_free' [-Werror,-Wunused-function]

BUG=chromium:702741
TEST=build with clang for gru

Change-Id: Ib14b348061a25b523e6b7db6a96993e525f40c1d
Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/508106
Reviewed-by: Guenter Roeck <groeck@chromium.org>