FROMGIT: r8152: Remove unused function usb_ocp_read()
The function is not used, removing it fixes the following warning when
building with clang:

drivers/net/usb/r8152.c:825:5: error: unused function 'usb_ocp_read'
    [-Werror,-Wunused-function]

BUG=chromium:702741
TEST=build with clang for pyro

Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from git.kernel.orgd davem/net-next master
commit db646cc0aefbc5da0b9699ed40d4402e01245f57)

Change-Id: I8a0e7b98b39e94e0ba7ad655c170b0b24bbce028
Reviewed-on: https://chromium-review.googlesource.com/508444
Commit-Ready: Matthias Kaehlcke <mka@chromium.org>
Tested-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-by: Douglas Anderson <dianders@chromium.org>