CHROMIUM: MALI: Remove unused function __compile_time_asserts()
This fixes the following warning when building with clang:

drivers/gpu/arm/midgard/mali_kbase_core_linux.c:117:20: error:
    unused function '__compile_time_asserts'

BUG=chromium:702741
TEST=build for gru with clang

Change-Id: I87e05c7d804e21c2084922b345c0dfed97623be1
Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/511802
Reviewed-by: Stéphane Marchesin <marcheu@chromium.org>