CHROMIUM: Update MALI_MIDGARD dependencies
ToT as well as the tail of currently pending patch series fails to build
MALI_MIDGARD as module. Trying to do so results in the following errors.

ERROR: "sync_pt_create" [drivers/gpu/arm/midgard/mali_kbase.ko] undefined!
ERROR: "sync_timeline_put" [drivers/gpu/arm/midgard/mali_kbase.ko] undefined!
ERROR: "sync_timeline_create" [drivers/gpu/arm/midgard/mali_kbase.ko] undefined!
ERROR: "fence_to_sync_pt" [drivers/gpu/arm/midgard/mali_kbase.ko] undefined!

Instead of trying to chase its module build errors, mark MALI_MIDGARD as bool
to clarify that it is not expected to be buildable as module.

Also, mark its dependencies on DRM and THERMAL.

BUG=chromium:714307
TEST=Test various build configuration options

Change-Id: I99df896dbd8c674bcf98cc41e0cae50cef49cd6f
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/539955
Reviewed-by: Dominik Behr <dbehr@chromium.org>
Reviewed-by: Douglas Anderson <dianders@chromium.org>