CHROMIUM: MALI: mark MALI_MIDGARD_DVFS as BROKEN
Commit b70a3434efa7 ("CHROMIUM: MALI: platform/rk: update the specific code")
broke MALI_MIDGARD_DVFS by dropping some legacy code:

drivers/built-in.o: In function `kbase_pm_get_dvfs_action':
drivers/gpu/arm/midgard/backend/gpu/mali_kbase_pm_metrics.c:306: undefined reference to `kbase_platform_dvfs_event'

That's legacy code, and AFAICT we don't plan to support it, so let's enforce
that.

BUG=chrome-os-partner:51368
TEST=build for veyron; can't enable MALI_MIDGARD_DVFS

Change-Id: Iabe5888f59146878ad7b7849a28ebfb4de75680d
Signed-off-by: Brian Norris <briannorris@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/349748
Reviewed-by: Douglas Anderson <dianders@chromium.org>