CHROMIUM: drm/armada: Mark as BROKEN
It no longer builds due to incomplete drm backports.

drivers/gpu/drm/armada/armada_crtc.c: In function 'armada_drm_crtc_calc_fb':
drivers/gpu/drm/armada/armada_crtc.c:172:38: error:
	'struct drm_framebuffer' has no member named 'bits_per_pixel'

Mark it as BROKEN to indicate that it is not expected to work, much less
supported.

BUG=b:36446508
TEST=None

Change-Id: I371657d340790d7ff431e5b332f6f3771626a15c
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/569070
Reviewed-by: Sonny Rao <sonnyrao@chromium.org>