CHROMIUM: syscall: Export sys_setpriority
Builds with CONFIG_ALT_SYSCALL_CHROMIUMOS=m fail with

ERROR: "sys_setpriority" [security/chromiumos/alt-syscall.ko] undefined!

BUG=b/29188854
TEST=Build image with CONFIG_ALT_SYSCALL_CHROMIUMOS=m

Fixes: ca6177fd6ccf ("CHROMIUM: alt-syscall: override setpriority syscall for Android")
Change-Id: Id6a581347265debd0d95913425535ce136417107
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/355732
Reviewed-by: Dylan Reid <dgreid@chromium.org>