UPSTREAM: reset: Make reset_control_ops const
The ops pointer is holding a pointer to a structure that is usually not
modified. Make it const.

Signed-off-by: Maxime Ripard <maxime.ripard@free-electrons.com>
Signed-off-by: Philipp Zabel <p.zabel@pengutronix.de>
(cherry picked from commit 203d4f347d86aa9e78342457aa7a3844c4fadd1d)

BUG=none
TEST=build arm-generic

[resolves this warning/error:
drivers/clk/rockchip/softrst.c: In function 'rockchip_register_softrst':
drivers/clk/rockchip/softrst.c:110:21: error: assignment discards 'const' qualifier from pointer target type [-Werror]
   softrst->rcdev.ops = &rockchip_softrst_ops;
                      ^
 cc1: all warnings being treated as errors
]

Change-Id: Ibe76c6f032d3efc887d43dcc2054259be5b39e4a
Signed-off-by: Brian Norris <briannorris@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/339743
Reviewed-by: Guenter Roeck <groeck@google.com>