FIXUP: HACK: PCI: rockchip: use PCIe core LANE MAP for lane idling
arm:allmodconfig and arm64:allmodconfig fail to build with

drivers/built-in.o: In function `rockchip_pcie_init_port':
	undefined reference to `rockchip_pcie_phy_laneoff'

The Rockchip PCIe code now calls rockchip_pcie_phy_laneoff() and thus
depends on PHY_ROCKCHIP_PCIE.

BUG=chrome-os-partner:55108, chrome-os-partner:57892
TEST=boot Kevin, check PCIe/Wifi
TEST=Build arm64:allmodconfig and/or arm:allmodconfig

Change-Id: Iaad2ad24915ccf90a0067ff9770048544c16ae4f
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/391249
Reviewed-by: Brian Norris <briannorris@chromium.org>