FIXUP: drm: Add new DRM_IOCTL_MODE_GETPLANE2
Commit 4d350e05a74f ("drm: Add new DRM_IOCTL_MODE_GETPLANE2") adds new
parameters to drm_universal_plane_init(), but missed some callers. This
results in build failures such as

drivers/gpu/drm/msm/mdp/mdp4/mdp4_plane.c: In function 'mdp4_plane_init':
drivers/gpu/drm/msm/mdp/mdp4/mdp4_plane.c:399:8: error:
	incompatible type for argument 7 of 'drm_universal_plane_init'

drivers/gpu/drm/msm/mdp/mdp4/mdp4_plane.c:399:8: error:
	too few arguments to function drm_universal_plane_init

BUG=chrome-os-partner:56407
TEST=Build arm:allmodconfig, arm:multi_v7_defconfig, and/or arm64:allmodconfig

Change-Id: Ieff0ed1644ceb549e80ed65c48757a27c04a9c53
Fixes: 4d350e05a74f ("drm: Add new DRM_IOCTL_MODE_GETPLANE2")
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/422957
Commit-Ready: Kristian H. Kristensen <hoegsberg@chromium.org>
Reviewed-by: Kristian H. Kristensen <hoegsberg@chromium.org>