CHROMIUM: extcon: add linux/sched.h header file
Fix compilation on x86-64 allmodconfig:
drivers/extcon/extcon-cros_ec.c: In function extcon_cros_ec_detect_cable:
include/linux/wait.h:167:39: error: TASK_NORMAL undeclared (first use in this function)
 #define wake_up_all(x)   __wake_up(x, TASK_NORMAL, 0, NULL)

Signed-off-by: Nicolas Boichat <drinkcat@chromium.org>

BUG=chromium:474744
TEST=x86-64 allmodconfig

Change-Id: Ice60b9f772e2f68c3287e7a76c7c4f31519bf43a
Reviewed-on: https://chromium-review.googlesource.com/301100
Commit-Ready: Nicolas Boichat <drinkcat@chromium.org>
Tested-by: Nicolas Boichat <drinkcat@chromium.org>
Reviewed-by: Alec Berg <alecaberg@chromium.org>

Conflicts:
	drivers/extcon/extcon-cros_ec.c

[rebase44(groeck): Resolved conflicts]
Signed-off-by: Guenter Roeck <groeck@chromium.org>