BACKPORT: drm: Remove unused drm_device from drm_gem_object_lookup()
drm_gem_object_lookup() has never required the drm_device for its file
local translation of the user handle to the GEM object. Let's remove the
unused parameter and save some space.

Signed-off-by: Chris Wilson <chris@chris-wilson.co.uk>
Cc: dri-devel@lists.freedesktop.org
Cc: Dave Airlie <airlied@redhat.com>
Cc: Daniel Vetter <daniel.vetter@ffwll.ch>
[danvet: Fixup kerneldoc too.]
Signed-off-by: Daniel Vetter <daniel.vetter@ffwll.ch>

(cherry picked from commit a8ad0bd84f986072314595d05444719fdf29e412)
from topic/drm-misc-2016-05-17
Signed-off-by: Tarun <tarun.vyas@intel.com>

BUG=b:36446508
TEST=No regressions in KBL and APL based devices

 Conflicts: [Tarun: Resolve the minor conflicts due to context deltas
 		and modify the drm_gem_object_lookup() signature to
		remove the drm_device argument. Refrain from making any
		other modifications.]
	drivers/gpu/drm/amd/amdgpu/amdgpu_bo_list.c
	drivers/gpu/drm/amd/amdgpu/amdgpu_cs.c
	drivers/gpu/drm/armada/armada_gem.c
	drivers/gpu/drm/etnaviv/etnaviv_drv.c
	drivers/gpu/drm/exynos/exynos_drm_gem.c
	drivers/gpu/drm/gma500/gem.c
	drivers/gpu/drm/gma500/gma_display.c
	drivers/gpu/drm/tegra/gem.c
	drivers/gpu/drm/vc4/vc4_bo.c
	drivers/gpu/drm/vc4/vc4_gem.c

 Modified: [Tarun: The drm_gem_object_lookup() is called in all of these
		 files. Modify the signature to remove the drm_device
		 argument]
 	drivers/gpu/drm/cirrus/cirrus_mode.c
	drivers/gpu/drm/evdi/evdi_cursor.c
	drivers/gpu/drm/evdi/evdi_fb.c
	drivers/gpu/drm/evdi/evdi_gem.c
	drivers/gpu/drm/udl/udl_cursor.c

FIXUP: drm: remove unused dev variables

After drm_gem_object_lookup() was changed along with all its callers,
we have several drivers that have unused variables:

drm/armada/armada_crtc.c: In function 'armada_drm_crtc_cursor_set':
drm/armada/armada_crtc.c:900:21: error: unused variable 'dev' [-Werror=unused-variable]
drm/nouveau/nouveau_gem.c: In function 'validate_init':
drm/nouveau/nouveau_gem.c:371:21: error: unused variable 'dev' [-Werror=unused-variable]
drm/nouveau/nv50_display.c: In function 'nv50_crtc_cursor_set':
drm/nouveau/nv50_display.c:1308:21: error: unused variable 'dev' [-Werror=unused-variable]
drm/radeon/radeon_cs.c: In function 'radeon_cs_parser_relocs':
drm/radeon/radeon_cs.c:77:21: error: unused variable 'ddev' [-Werror=unused-variable]

This fixes all the instances I found with ARM randconfig builds so far.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: a8ad0bd84f98 ("drm: Remove unused drm_device from drm_gem_object_lookup()")
Signed-off-by: Daniel Vetter <daniel.vetter@ffwll.ch>
Link: http://patchwork.freedesktop.org/patch/msgid/1463587653-3035181-6-git-send-email-arnd@arndb.de
(cherry picked from commit c6740c9c9e914742fd2ec159142c40701f7df966)
from v4.7-rc1
Signed-off-by: Tarun <tarun.vyas@intel.com>

FIXUP: [Tarun: This commit has been squashed with the "BACKPORT: drm: Remove
unused drm_device from drm_gem_object_lookup()" commit b/c it serves
as a build fixup for that commit.]

Change-Id: I9270562ebfca2922cb9b0ebe443f6949fefa14c0
Reviewed-on: https://chromium-review.googlesource.com/459985
Commit-Ready: Sean Paul <seanpaul@google.com>
Tested-by: Sean Paul <seanpaul@chromium.org>
Tested-by: Sean Paul <seanpaul@google.com>
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Reviewed-by: Sean Paul <seanpaul@google.com>