CHROMIUM: cpuidle: governor: menu: Mark get_loadavg() as __maybe_unused
Commit 4dedd9f12470 ("cpuidle: governor: menu: don't use loadavg")
commented the only call to get_loadavg(), leaving it unused. Adding the
attribute fixes the following warning when building with clang:

drivers/cpuidle/governors/menu.c:137:19: error: unused function
'get_loadavg' [-Werror,-Wunused-function]

BUG=chromium:702741
TEST=build with clang for gru

Change-Id: Icaf86f0fc257efc458fcdf4eeb114c0243e63123
Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/508105
Reviewed-by: Guenter Roeck <groeck@chromium.org>