FIXUP: CHROMIUM: rockchip: pd: rockchip: register notify to dmc dirver
pd_register_notify_to_dmc() is called from devfreq/rk3399_dmc which
can be built as module. Doing so results in the following build failure.

ERROR: "pd_register_notify_to_dmc" [drivers/devfreq/rk3399_dmc.ko] undefined!

BUG=chrome-os-partner:54651
TEST=Declare CONFIG_ARM_RK3399_DMC_DEVFREQ=m and build image

Change-Id: Ib3646097eb5bf35de508bba93659dd7d2844f36e
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/423210
Reviewed-by: Matthias Kaehlcke <mka@chromium.org>