FROMGIT: ASoC: cht_bsw_max98090_ti: Remove unused function cht_get_codec_dai()
Looks like the function has never been used since it was added by commit
17119a465706 ("ASoC: Intel: Add Cherrytrail & Braswell machine driver
cht_bsw_max98090_ti"). Removing it fixes the following warning when
building with clang:

sound/soc/intel/boards/cht_bsw_max98090_ti.c:42:35: error: unused
    function 'cht_get_codec_dai' [-Werror,-Wunused-function]

BUG=chromium:702741
TEST=build for pyro with clang

Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from git.kernel.org broonie/sound for-next
commit 140385d87adce8d00864667f5132770ac5a13dac)

Change-Id: If735683d8206f61a7aafde3cd794dc7a8f10276b
Reviewed-on: https://chromium-review.googlesource.com/513441
Commit-Ready: Matthias Kaehlcke <mka@chromium.org>
Tested-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-by: Douglas Anderson <dianders@chromium.org>