FIXUP: CHROMIUM: cros_ec: fix reference of ec_name
CROS_EC_DEV_NAME is defined in linux/mfd/cros_ec_dev.h

Fixes build error:
drivers/input/keyboard/cros_ec_keyb.c: In function 'cros_ec_keyb_probe':
drivers/input/keyboard/cros_ec_keyb.c:271:15: error: 'CROS_EC_DEV_NAME' undeclared (first use in this function)
  idev->name = CROS_EC_DEV_NAME;
               ^

Signed-off-by: Daniel Kurtz <djkurtz@chromium.org>

BUG=chrome-os-partner:38563
TEST=emerge-oak chromeos-kernel-3_18

Change-Id: Idd45cd84679199dc23ceea3ea8bbae4cec12e77c