UPSTREAM: drm_mode.h: use __u32 and __u64 from linux/types.h
Fixes userspace compilation error:

drm/drm_mode.h:472:2: error: unknown type name uint32_t

Signed-off-by: Mikko Rapeli <mikko.rapeli@iki.fi>
(cherry picked from commit 05623b7fcaf20886721307de10547d3f91235186)
from v4.5-rc1
Signed-off-by: Tarun <tarun.vyas@intel.com>

BUG=b:36446508
TEST=No regressions in KBL and APL based devices

Change-Id: Ieb7666083b9397bb02da03122fdc838569bad43c
Reviewed-on: https://chromium-review.googlesource.com/510273
Commit-Ready: Sean Paul <seanpaul@chromium.org>
Tested-by: Sean Paul <seanpaul@chromium.org>
Reviewed-by: Sean Paul <seanpaul@chromium.org>