FIXUP: FROMLIST: drm: mediatek: change the variable type of rdma threshold
Build on arm (32 bit) kernels results in

ERROR: "__aeabi_uldivmod" [drivers/gpu/drm/mediatek/mediatek-drm.ko] undefined!

due to an unhandled 64 bit divide operation.

BUG=b:36082950
TEST=Boot to UI on Rowan and do not see any flicker on panel.

Signed-off-by: Guenter Roeck <groeck@chromium.org>

Change-Id: I9a86fe80cfad915c61eb08cfb0069b32a3d5b623
Reviewed-on: https://chromium-review.googlesource.com/543916
Commit-Ready: Guenter Roeck <groeck@chromium.org>
Tested-by: Guenter Roeck <groeck@chromium.org>
Reviewed-by: Bibby Hsieh <bibby.hsieh@mediatek.com>
Reviewed-by: Daniel Kurtz <djkurtz@chromium.org>