DRM: Armada: update dma_buf_export use
The dma_buf_export function was updated in commit 4bcec44ffaf9 'dma-buf: use
reservation objects' to take a reservation object parameter; update Armada
export method accordingly.

This fixes the following compilation error:

  drivers/gpu/drm/armada/armada_gem.c: In function ‘armada_gem_prime_export’:
  drivers/gpu/drm/armada/armada_gem.c:544:16: error: macro "dma_buf_export" requires 5 arguments, but only 4 given

Signed-off-by: Vincent Stehlé <vincent.stehle@laposte.net>
Cc: Russell King <rmk+kernel@arm.linux.org.uk>
Cc: David Airlie <airlied@linux.ie>
Cc: Maarten Lankhorst <maarten.lankhorst@canonical.com>
Cc: Sumit Semwal <sumit.semwal@linaro.org>