UPSTREAM: soc: qcom/spm: shut up uninitialized variable warning
gcc warns about the 'found' variable possibly being used uninitialized:

drivers/soc/qcom/spm.c: In function 'spm_dev_probe':
drivers/soc/qcom/spm.c:305:5: error: 'found' may be used uninitialized in this function [-Werror=maybe-uninitialized]

However, the code is correct because we know that there is
always at least one online CPU. This initializes the 'found'
variable to zero before the loop so the compiler knows
it does not have to warn about it.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
(cherry picked from commit 00affcac69c7aae6c2cfcbc71f724e1c16d0b445)
Signed-off-by: Guenter Roeck <groeck@chromium.org>

Change-Id: I69c8f0acab2cee0158296a4be0aff918cf81ad95
Reviewed-on: https://chromium-review.googlesource.com/331547
Reviewed-by: Filipe Brandenburger <filbranden@chromium.org>
Tested-by: Guenter Roeck <groeck@chromium.org>