ANDROID: DEBUG: cpufreq: fix cpu_capacity tracing build for non-smp systems
cpu curr capacity can only be traced for SMP systems. Non-SMP builds
will fail with:

drivers/cpufreq/cpufreq.c: In function cpufreq_freq_transition_begin:
drivers/cpufreq/cpufreq.c:438:22: error: implicit declaration of function capacity_curr_of [-Werror=implicit-function-declaration]
   trace_cpu_capacity(capacity_curr_of(cpu), cpu);
                      ^
BUG=chromium:676723
TEST=Build with CPU_FREQ enabled and SMP disabled

Fixes: Change-Id: Icd0930d11068fcb7d2b6a9a48e7ed974904e1081
       ("DEBUG: sched,cpufreq: add cpu_capacity change tracepoint")
Signed-off-by: Amit Pundir <amit.pundir@linaro.org>
[jstultz: Cherry-picked from common/android-3.18]
Signed-off-by: John Stultz <john.stultz@linaro.org>
(cherry picked from commit 6c7e03dde14e5074134f47d9ec3dea7de24e4e58)
Signed-off-by: Guenter Roeck <groeck@chromium.org>

Change-Id: I68511af87351c731cd6596856fbb9ffb7185af2d
Reviewed-on: https://chromium-review.googlesource.com/423332
Commit-Ready: Guenter Roeck <groeck@chromium.org>
Tested-by: Guenter Roeck <groeck@chromium.org>
Reviewed-by: Sonny Rao <sonnyrao@chromium.org>