FIXUP: WIP / CHROMIUM: PCI: Rockchip: Add Rockchip PCIe controller support
Building the driver as module results in

ERROR: "pci_remap_iospace" [drivers/pci/host/pcie-rockchip.ko] undefined!

pci_remap_iospace() is declared as __weak. Maybe such a symbol can be
exported, maybe not. Don't risk it and always build the driver into
the kernel.

BUG=chrome-os-partner:52323
TEST=Check wifi on rk3399 kevin

Change-Id: I4fd43431eaf4fd58b247d60b509f307633072d89
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/359280
Reviewed-by: Douglas Anderson <dianders@chromium.org>