UPSTREAM: drm: mediatek: fixup drm_gem_object_lookup API change
The drm_gem_object_lookup() function prototype changed while this
driver was added, so it fails to build now:

drivers/gpu/drm/mediatek/mtk_drm_gem.c: In function 'mtk_drm_gem_dumb_map_offset':
drivers/gpu/drm/mediatek/mtk_drm_gem.c:142:30: error: passing argument 1 of 'drm_gem_object_lookup' from incompatible pointer type [-Werror=incompatible-pointer-types]
  obj = drm_gem_object_lookup(dev, file_priv, handle);

This fixes the new caller as well.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: a8ad0bd84f98 ("drm: Remove unused drm_device from drm_gem_object_lookup()")
Signed-off-by: Daniel Vetter <daniel.vetter@ffwll.ch>
Link: http://patchwork.freedesktop.org/patch/msgid/1463587653-3035181-4-git-send-email-arnd@arndb.de
(cherry picked from commit de4ae068ebf599f46ddfc5f8541a302226230267)
Signed-off-by: Wayne Boyer <wayne.boyer@intel.com>

BUG=b:36446508
TEST=No regressions in KBL and APL based devices

Change-Id: I00ab74819487fb8813ec39c36186e0603a7606f3
Reviewed-on: https://chromium-review.googlesource.com/505221
Commit-Ready: Wayne Boyer <wayne.boyer@intel.corp-partner.google.com>
Tested-by: Sean Paul <seanpaul@google.com>
Reviewed-by: Sean Paul <seanpaul@google.com>