FIXUP: BACKPORT: staging/android: rename sync_fence to sync_file
In file included from drivers/gpu/arm/midgard/mali_kbase.h:25:0,
                 from drivers/gpu/arm/midgard/mali_kbase_softjobs.c:20:
drivers/gpu/arm/midgard/mali_kbase_softjobs.c:
		In function 'kbase_process_soft_job':
drivers/gpu/arm/midgard/mali_kbase_softjobs.c:1175:27: error:
		'struct kbase_jd_atom' has no member named 'fence'

'fence' has been renamed to 'sfile'.

BUG=chromium:714307
TEST=Build image with CONFIG_MALI_DEBUG enabled

Change-Id: I5a7493c2066b5dcf185b1eedba0cdd3efd9d027b
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/527294
Reviewed-by: Dominik Behr <dbehr@chromium.org>
Reviewed-by: Sonny Rao <sonnyrao@chromium.org>