video: Mark ADF as BROKEN
With recent staging/android changes, the ADF component no longer compiles.

drivers/video/adf/adf_client.c: In function adf_sw_complete_fence:
drivers/video/adf/adf_client.c:327:5: warning:
		assignment from incompatible pointer type
drivers/video/adf/adf_client.c:330:2: error:
		implicit declaration of function sync_fence_create
drivers/video/adf/adf_client.c:330:17: warning:
		assignment makes pointer from integer without a cast
drivers/video/adf/adf_client.c:337:2: error:
		implicit declaration of function sync_pt_free

It also appears to be unused, and does not exist upstream. Mark it as BROKEN.

BUG=None
TEST=Build x86_64:allmodconfig

Change-Id: I22291088edb51c6f8471749a17dd6002e41540d5
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/527252
Reviewed-by: Sonny Rao <sonnyrao@chromium.org>