CHROMIUM: platform: x86: chromeos_acpi: select NVRAM
The missing dependency can result in the following build error.

drivers/built-in.o: In function `chromeos_vbc_nvram_write':
chromeos_acpi.c:(.text+0x26ed72): undefined reference to `nvram_read_byte'
chromeos_acpi.c:(.text+0x26edaf): undefined reference to `nvram_write_byte'
drivers/built-in.o: In function `chromeos_vbc_nvram_read':
chromeos_acpi.c:(.text+0x26ee8c): undefined reference to `nvram_read_byte'

Have ACPI_CHROMEOS select NVRAM instead of depending on it to ensure
that NVRAM is built into the kernel.

Fixes: 3d9d1534fb593 ("CHROMIUM: Introduce chromeos platform layer")
BUG=chromium:583462
TEST=None (build)

Change-Id: I04f94d7cc4abb372bf9020e50dc51fc61dfe1414
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325521